name: draft.yml

on:
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - run: |
              find . -mindepth 1 ! -name 'action.yml' ! -name 'Dockerfile' -exec rm -rf {} +
              echo "hello world" > hello.txt

        - name: Run Action
          id: run-action
          uses: ./
          with:
              files: |
                  hello.txt
